// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC30Vpz3_sU15HsDlqMuEI4ZJKlqHhkSkE',
    appId: '1:87084821589:web:1309facb56dc287babb8dc',
    messagingSenderId: '87084821589',
    projectId: 'exotic-gaming-and-cafe',
    authDomain: 'exotic-gaming-and-cafe.firebaseapp.com',
    storageBucket: 'exotic-gaming-and-cafe.firebasestorage.app',
    measurementId: 'G-8XBBM17F5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvHR9k85AfVsO6KZrZryKl2cmej1H6Kh0',
    appId: '1:87084821589:android:8252c30aea6ba5f8abb8dc',
    messagingSenderId: '87084821589',
    projectId: 'exotic-gaming-and-cafe',
    storageBucket: 'exotic-gaming-and-cafe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFMdpvRMTH74jk2_PDMhTuE-63LoBYSbM',
    appId: '1:87084821589:ios:79afc7883006180babb8dc',
    messagingSenderId: '87084821589',
    projectId: 'exotic-gaming-and-cafe',
    storageBucket: 'exotic-gaming-and-cafe.firebasestorage.app',
    iosBundleId: 'com.example.apk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFMdpvRMTH74jk2_PDMhTuE-63LoBYSbM',
    appId: '1:87084821589:ios:79afc7883006180babb8dc',
    messagingSenderId: '87084821589',
    projectId: 'exotic-gaming-and-cafe',
    storageBucket: 'exotic-gaming-and-cafe.firebasestorage.app',
    iosBundleId: 'com.example.apk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC30Vpz3_sU15HsDlqMuEI4ZJKlqHhkSkE',
    appId: '1:87084821589:web:29130638c79eda96abb8dc',
    messagingSenderId: '87084821589',
    projectId: 'exotic-gaming-and-cafe',
    authDomain: 'exotic-gaming-and-cafe.firebaseapp.com',
    storageBucket: 'exotic-gaming-and-cafe.firebasestorage.app',
    measurementId: 'G-K0T2CJY16D',
  );
}
